name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

  flake:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: "experimental-features = nix-command flakes"
    - name: Build flake
      run: nix build --print-build-logs
